### ISSUE TITLE
Requirements error(s)?, specific to release 0.5.2. 

### ISSUE THREAD

**Issue by tarorororororo** [hwsmm/cosutrainer#1]
I am getting the following error on release 0.5.2, and went back to 0.3.0 which has worked fine, but can't run the GUI. 

```
[shizuru@shizuru-systemproductname cosu-trainer-bintest1]$ cosu-trainer
Not enough arguments.
[shizuru@shizuru-systemproductname cosu-trainer-bintest1]$ ./cosu-trainer
./cosu-trainer: error while loading shared libraries: libSoundTouch.so.1: cannot open shared object file: No such file or directory
```

**Comment by tarorororororo** [comment]
I realized the issue was missing requirements (libsoundtouch listed on the github) so I made sure to build it properly. I have never heard of meson before, so was confused what to do. I downloaded meson from AUR and then everything worked fine. Please excuse my incompetence, I am new to linux still... LOL thanks for the program.

**Comment by hwsmm** [comment]
Thank you for using my program!

I think it's because my build environment is too old for most (new) systems. I may update it to fit new systems at some time. but I also provide packages [here](https://software.opensuse.org//download.html?project=home%3Ahwsnemo%3Apackaged-wine-osu&package=cosu-trainer) that should work well on most distros. That's why I thought it'd be still fine to use old versions, but that's rather lame I guess... I'll try to update it when I release next version since most osu! players on Linux use Arch anyway lol
